import { Geist, Geist_Mono, Sora, Poppins } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
})

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight:['400']
  })

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

// app/layout.js
export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body 
        className={`
          ${geistSans.className} 
          ${geistMono.className} 
          ${sora.className}
          ${poppins.className}
          transition-colors 
          duration-500
        `}
      >
        <div className={poppins.className}>
          {children}
        </div>
      </body>
    </html>
  );
}
